{% set name = "pyacvd" %}
{% set version = "0.3.1" %}

package:
  name: pyacvd
  version: {{ version }}

source:
  url: https://github.com/pyvista/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ab824260cea2912c51e2b2fc92d6f20b79b9ca72dcff9eec2459b3e20469b8f9

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python  # [build_platform != target_platform]
    # there is no cross-python for linux-64 -> win-64
    - cross-python_{{ target_platform }}  # [build_platform != target_platform and not target_platform == "win-64"]
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - scikit-build-core
    - nanobind
    - numpy
    - pip
    - python
  run:
    - python
    - pyvista >=0.37.0
    - pykdtree

test:
  imports:
    - pyacvd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyvista/pyacvd
  summary: Uniformly remeshes surface meshes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akaszynski
    - ytausch
